### ISSUE TITLE
Unable to browse in Kodi v16.0 (Jarvis)

### ISSUE THREAD

**Issue by nylitz** [VioletRed/kodi-urplay#1]
When clicking Programs A-Ö I get the following error message:

`22:23:23 T:5088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\Mattias\AppData\Roaming\Kodi\addons\kodi-urplay-master\default.py", line 263, in <module>
                                                viewAtoO()
                                              File "C:\Users\Mattias\AppData\Roaming\Kodi\addons\kodi-urplay-master\default.py", line 87, in viewAtoO
                                                for program in programs:
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--`
`22:23:23 T:7180   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.urplay/?mode=a-o`
`22:23:23 T:7180   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.urplay/?mode=a-o) failed`

I'm running Kodi v16.0 (Jarvis).

**Comment by VioletRed** [comment]
SVT updated UR's site, they removed the old category menu, and the A-Ö link. I haven't have time to make it work again because it would probably require a mayor re-writing.
